package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.bumptech.glide.d;
import e6.m2;
import e6.o3;
import e6.q3;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-90bdb1e633fc7deccf1f2262b96244d51f1613c31a781dbcb0c26e7e72a99457 */
/* JADX INFO: loaded from: classes.dex */
public final class zzbus extends h7.a {
    public static final Parcelable.Creator<zzbus> CREATOR = new zzbut();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final m2 zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbmb zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final o3 zzc;
    public final q3 zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final i6.a zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbfn zzy;
    public final List zzz;

    public zzbus(int i, Bundle bundle, o3 o3Var, q3 q3Var, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, i6.a aVar, Bundle bundle2, int i10, List list, Bundle bundle3, boolean z4, int i11, int i12, float f10, String str5, long j4, String str6, List list2, String str7, zzbfn zzbfnVar, List list3, long j10, String str8, float f11, boolean z10, int i13, int i14, boolean z11, String str9, String str10, boolean z12, int i15, Bundle bundle4, String str11, m2 m2Var, boolean z13, Bundle bundle5, String str12, String str13, String str14, boolean z14, List list4, String str15, List list5, int i16, boolean z15, boolean z16, boolean z17, ArrayList arrayList, String str16, zzbmb zzbmbVar, String str17, Bundle bundle6) {
        this.zza = i;
        this.zzb = bundle;
        this.zzc = o3Var;
        this.zzd = q3Var;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = aVar;
        this.zzl = bundle2;
        this.zzm = i10;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z4;
        this.zzq = i11;
        this.zzr = i12;
        this.zzs = f10;
        this.zzt = str5;
        this.zzu = j4;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.EMPTY_LIST : Collections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = zzbfnVar;
        this.zzA = j10;
        this.zzB = str8;
        this.zzC = f11;
        this.zzH = z10;
        this.zzD = i13;
        this.zzE = i14;
        this.zzF = z11;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z12;
        this.zzK = i15;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = m2Var;
        this.zzO = z13;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z14;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i16;
        this.zzY = z15;
        this.zzZ = z16;
        this.zzaa = z17;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzbmbVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int i10 = this.zza;
        int iP = d.P(20293, parcel);
        d.R(parcel, 1, 4);
        parcel.writeInt(i10);
        d.C(parcel, 2, this.zzb, false);
        d.J(parcel, 3, this.zzc, i, false);
        d.J(parcel, 4, this.zzd, i, false);
        d.K(parcel, 5, this.zze, false);
        d.J(parcel, 6, this.zzf, i, false);
        d.J(parcel, 7, this.zzg, i, false);
        d.K(parcel, 8, this.zzh, false);
        d.K(parcel, 9, this.zzi, false);
        d.K(parcel, 10, this.zzj, false);
        d.J(parcel, 11, this.zzk, i, false);
        d.C(parcel, 12, this.zzl, false);
        int i11 = this.zzm;
        d.R(parcel, 13, 4);
        parcel.writeInt(i11);
        d.M(parcel, 14, this.zzn);
        d.C(parcel, 15, this.zzo, false);
        boolean z4 = this.zzp;
        d.R(parcel, 16, 4);
        parcel.writeInt(z4 ? 1 : 0);
        int i12 = this.zzq;
        d.R(parcel, 18, 4);
        parcel.writeInt(i12);
        int i13 = this.zzr;
        d.R(parcel, 19, 4);
        parcel.writeInt(i13);
        float f10 = this.zzs;
        d.R(parcel, 20, 4);
        parcel.writeFloat(f10);
        d.K(parcel, 21, this.zzt, false);
        long j4 = this.zzu;
        d.R(parcel, 25, 8);
        parcel.writeLong(j4);
        d.K(parcel, 26, this.zzv, false);
        d.M(parcel, 27, this.zzw);
        d.K(parcel, 28, this.zzx, false);
        d.J(parcel, 29, this.zzy, i, false);
        d.M(parcel, 30, this.zzz);
        long j10 = this.zzA;
        d.R(parcel, 31, 8);
        parcel.writeLong(j10);
        d.K(parcel, 33, this.zzB, false);
        float f11 = this.zzC;
        d.R(parcel, 34, 4);
        parcel.writeFloat(f11);
        int i14 = this.zzD;
        d.R(parcel, 35, 4);
        parcel.writeInt(i14);
        int i15 = this.zzE;
        d.R(parcel, 36, 4);
        parcel.writeInt(i15);
        boolean z10 = this.zzF;
        d.R(parcel, 37, 4);
        parcel.writeInt(z10 ? 1 : 0);
        d.K(parcel, 39, this.zzG, false);
        boolean z11 = this.zzH;
        d.R(parcel, 40, 4);
        parcel.writeInt(z11 ? 1 : 0);
        d.K(parcel, 41, this.zzI, false);
        boolean z12 = this.zzJ;
        d.R(parcel, 42, 4);
        parcel.writeInt(z12 ? 1 : 0);
        int i16 = this.zzK;
        d.R(parcel, 43, 4);
        parcel.writeInt(i16);
        d.C(parcel, 44, this.zzL, false);
        d.K(parcel, 45, this.zzM, false);
        d.J(parcel, 46, this.zzN, i, false);
        boolean z13 = this.zzO;
        d.R(parcel, 47, 4);
        parcel.writeInt(z13 ? 1 : 0);
        d.C(parcel, 48, this.zzP, false);
        d.K(parcel, 49, this.zzQ, false);
        d.K(parcel, 50, this.zzR, false);
        d.K(parcel, 51, this.zzS, false);
        boolean z14 = this.zzT;
        d.R(parcel, 52, 4);
        parcel.writeInt(z14 ? 1 : 0);
        List list = this.zzU;
        if (list != null) {
            int iP2 = d.P(53, parcel);
            int size = list.size();
            parcel.writeInt(size);
            for (int i17 = 0; i17 < size; i17++) {
                parcel.writeInt(((Integer) list.get(i17)).intValue());
            }
            d.Q(iP2, parcel);
        }
        d.K(parcel, 54, this.zzV, false);
        d.M(parcel, 55, this.zzW);
        int i18 = this.zzX;
        d.R(parcel, 56, 4);
        parcel.writeInt(i18);
        boolean z15 = this.zzY;
        d.R(parcel, 57, 4);
        parcel.writeInt(z15 ? 1 : 0);
        boolean z16 = this.zzZ;
        d.R(parcel, 58, 4);
        parcel.writeInt(z16 ? 1 : 0);
        boolean z17 = this.zzaa;
        d.R(parcel, 59, 4);
        parcel.writeInt(z17 ? 1 : 0);
        d.M(parcel, 60, this.zzab);
        d.K(parcel, 61, this.zzac, false);
        d.J(parcel, 63, this.zzad, i, false);
        d.K(parcel, 64, this.zzae, false);
        d.C(parcel, 65, this.zzaf, false);
        d.Q(iP, parcel);
    }
}
