CREATE TABLE IF NOT EXISTS `notes` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `content` TEXT NOT NULL, `createdAt` INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS `notifications` (`notificationId` TEXT NOT NULL, `title` TEXT NOT NULL, `body` TEXT NOT NULL, `url` TEXT, `receivedAt` INTEGER NOT NULL, PRIMARY KEY(`notificationId`));
CREATE TABLE IF NOT EXISTS `checker_batches` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `gate` TEXT NOT NULL, `content` TEXT NOT NULL, `total` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS `temp_mail_history` (`email` TEXT NOT NULL, `createdAt` INTEGER NOT NULL, PRIMARY KEY(`email`));
